development:
  sessions:
    default:
      database: neuron_math_26_06_15_server
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: locomotive_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      # uri: <%= ENV['MONGOHQ_URL'] %>

